Repository triton-inference-server/python_backend, pull requests merged in 2024-08, with the labels that each got.

#373 refactor: Delete response factory after sending complete final
  src/response_sender.cc
  src/response_sender.h
Labels: PR: refactor

#372 perf: Release GIL during cancellation check
  src/pb_cancel.cc
Labels: PR: perf

#374 feat: Add histogram metric type
  README.md
  src/ipc_message.h
  src/metric.cc
  src/metric.h
  src/metric_family.cc
  src/metric_family.h
  src/pb_stub.cc
  src/pb_utils.h
  src/python_be.cc
Labels: enhancement

#376 feat: Add new histogram metric type (#374)
  README.md
  src/ipc_message.h
  src/metric.cc
  src/metric.h
  src/metric_family.cc
  src/metric_family.h
  src/pb_stub.cc
  src/pb_utils.h
  src/python_be.cc
Labels: cherry-pick
