Repository triton-inference-server/python_backend, pull requests merged in 2025-07, with the labels that each got.

#406 fix: Verify MemoryShm::byte_size inside shared memory boundary
  src/pb_memory.cc
  src/shm_manager.h
Labels: bug

#410 fix: Boundary check for MessageQueueShm head index (#405)
  CMakeLists.txt
  src/message_queue.h
  src/pb_bls_cancel.cc
  src/pb_cancel.cc
  src/pb_stub.cc
  src/pb_stub.h
  src/pb_stub_log.cc
  src/pb_stub_log.h
  src/pb_utils.h
Labels: cherry-pick, TPRD-1628, DLIS-8378

#409 fix: Remove shared memory key from the error response (#403)
  src/shm_manager.cc
Labels: cherry-pick, TPRD-1628, DLIS-8382
